### ISSUE TITLE
How to listen to events from channels

### ISSUE THREAD

**Issue by taboca** [pusher/pusher-http-python#101]
Apologies if I am not using proper wording but I am mainly comparing wording and architecture of documentation from different Pusher lib projects. 

The case I refer is the use case entitled as "Subscribing to channels" available at [Pusher Java Client # Subscribing to Channels](https://github.com/pusher/pusher-websocket-java#subscribing-to-channels).

I wonder if such use case is also available for programmers using this library project. From reading the read me, the closest thing to Subscription seems to be around the section entitled "Authenticating Channel Subscription". However some points seems unclear IMHO:

* "In order for users to subscribe to a private" — which users? 

* "The client will make a POST request to an endpoint (either "/pusher/auth" or any which you specify) with a body consisting of the channel's name and socket_id." — which client? 

I found quite confusing this specific section and the above points plus also the sample: 

```
auth = pusher.authenticate(

  channel=u"private-channel",

  socket_id=u"1234.12"
)
# return `auth` as a response
```

Which does not indicate what to do with such auth.

**Comment by hot-leaf-juice** [comment]
Hi @taboca, please see #69.

**Comment by taboca** [comment]
I see, the *server* function is a pushing system and the client is actual a subscriber, in the pusher terms. Quite odd, I would normally think, that priority is not for Client Python library. The other person, at #69 perhaps have a point "how do you know for sure you are not missing a ton of customers because you don't support websockets in Python?", but of course only Pusher employees are totally aware of all going on. 

My case is Google App Engine with Python BTW. 

But I would be able to find other workarounds for sure (Node in another server; other libs etc). Thanks a lot for being so helpful to find the bug and sorry. I looked in open issues and pulls only.

**Comment by hot-leaf-juice** [comment]
@taboca That's spot on :)

It might be worth checking out [this community python client library](https://github.com/nlsdfnbch/Pysher).
