### ISSUE TITLE
AsyncIOBackend throws error on aiohttp 2.3.9

### ISSUE THREAD

**Issue by zdexter** [pusher/pusher-http-python#106]
```
'ClientResponse' object has no attribute 'read_and_close'
```

more info: https://stackoverflow.com/questions/34971826/a-python-crawler-not-work-for-asyncio

probable solution: `yield from response.text()` instead of `yield from response.read_and_close()`.

**Comment by hot-leaf-juice** [comment]
Thanks for reporting this @zdexter! Got a fix pending in #107
