### ISSUE TITLE
Getting Data from Bitstamp

### ISSUE THREAD

**Issue by robinCantelli** [pusher/pusher-http-python#111]
I hope that you can help me because I'm getting kind of frustrated because of my incompetence;)

I want to get websocket data  from bitstamp to work with it. What I usually did was getting for example price data like ' bitStampTick = requests.get('https://www.bitstamp.net/api/v2/order_book/xrpeur')' and then did my calculations with the data. I put it in a loop so it kind of refreshes the data from time to time.

What I want to do now is receiving that same data (lists or dicts would be great) (even with other pairs) via websocket. I mean its real time data and in this case my code will get more efficient.

My problem is that even if I read through your tutorial I have no idea how to manage that. I'm coding for a wile now but this is my first time with websocket and pusher and I guess that I'm missing some principles about websocket here .

So I would be so glad if you could show me how to do what I want to achieve.

Thanks in advance

Robin

**Comment by WillSewell** [comment]
This library is only for interacting with the Pusher HTTP API. To interact with the Pusher WebSockets API, you should use a Pusher client library, e.g. https://github.com/nlsdfnbch/Pysher. I hope that helps!
