### ISSUE TITLE
AsyncIO backend does not process the HTTP response

### ISSUE THREAD

**Issue by agronholm** [pusher/pusher-http-python#121]
The backend imports `process_response` but never uses it. As such, it will never detect any bad HTTP responses.

**Comment by agronholm** [comment]
Thanks! Would you like me to also add the possibility to pass options to the aiohttp session? I used this method myself to add proxy support (`trust_env=True`) to the asyncio backend.

**Comment by WillSewell** [comment]
Yes that does sound useful! Could you show a code snippet of how this would be configured from the users point of view?

**Comment by agronholm** [comment]
Something along the lines of:
```python3
client = PusherClient(app_id, key, secret, session_options={'trust_env': True})
```

**Comment by agronholm** [comment]
Alternatively, something like `allow_proxies=True` might be simpler. It might also be fine to add that option by default since the default backend already respects the standard proxy env variables.
