### ISSUE TITLE
Error on app.py

### ISSUE THREAD

**Issue by vinodg912** [pusher/pusher-http-python#173]
Im getting error when running command `flask run`
I cant make chat app
Please help

![Screenshot_2021-05-06-21-11-38-81](https://user-images.githubusercontent.com/45803904/117326826-aa9f2b80-aeaf-11eb-90de-adc455067233.jpg)

**Comment by ben-pusher** [comment]
The error indicates an unexpected indent in your app. Have you confirmed the indentation of the code is correct?

**Comment by vinodg912** [comment]
> The error indicates an unexpected indent in your app. Have you confirmed the indentation of the code is correct?


I was copied all source code from your official website. 
And I do not understand what went wrong.I have followed all the steps

**Comment by ben-pusher** [comment]
Could you share the file? I suspect the code is correct but ,as the error states, there is an indent.

**Comment by vinodg912** [comment]
> Could you share the file? I suspect the code is correct but ,as the error states, there is an indent.

This is the source code. `cors = CORS(app)
    app.config['CORS_HEADERS'] = 'Content-Type'

    # configure pusher object
    pusher = pusher.Pusher(
   app_id = "pusher_key_hide for security"
key = "??"
secret = "??"
cluster = "??"
    ssl=True)

    @app.route('/')
    def index():
        return render_template('index.html')

    @app.route('/admin')
    def admin():
        return render_template('admin.html')

    @app.route('/new/guest', methods=['POST'])
    def guestUser():
        data = request.json
        pusher.trigger(u'general-channel', u'new-guest-details', {
            'name' : data['name'],
            'email' : data['email']
            })
        return json.dumps(data)

    @app.route("/pusher/auth", methods=['POST'])
    def pusher_authentication():
        auth = pusher.authenticate(channel=request.form['channel_name'],socket_i>
        return json.dumps(auth)

    if __name__ == '__main__':
        app.run(host='0.0.0.0', port=5000, debug=True)`

![Screenshot_2021-05-07-14-06-35-48](https://user-images.githubusercontent.com/45803904/117422977-d23cd500-af3d-11eb-8772-d3ba166d575c.jpg)
And this is the output error.

**Comment by vinodg912** [comment]
> Could you share the file? I suspect the code is correct but ,as the error states, there is an indent.

This is the source code..

`// File : ./app.py

    from flask import Flask, render_template, request, jsonify, make_response, j>
    from flask_cors import CORS
    from pusher import pusher
    import simplejson

    app = Flask(__name__)
    cors = CORS(app)
    app.config['CORS_HEADERS'] = 'Content-Type'

    # configure pusher object
    pusher = pusher.Pusher(
   app_id = "pusher_key hided for security"
key = "??"
secret = "??"
cluster = "??"
    ssl=True)

    @app.route('/')
    def index():
        return render_template('index.html')

    @app.route('/admin')
    def admin():
        return render_template('admin.html')

    @app.route('/new/guest', methods=['POST'])
    def guestUser():
        data = request.json
        pusher.trigger(u'general-channel', u'new-guest-details', {
            'name' : data['name'],
            'email' : data['email']
            })
        return json.dumps(data)

    @app.route("/pusher/auth", methods=['POST'])
    def pusher_authentication():
        auth = pusher.authenticate(channel=request.form['channel_name'],socket_i>
        return json.dumps(auth)

    if __name__ == '__main__':
        app.run(host='0.0.0.0', port=5000, debug=True)`



![Screenshot_2021-05-07-14-06-35-48](https://user-images.githubusercontent.com/45803904/117423454-5c853900-af3e-11eb-883f-db5d98bdbdec.jpg)
And this is the error output..

**Comment by ben-pusher** [comment]
It looks like the error has now changed. Reading the code you have shared and it seems there are a couple of errors. For example on line 1 you have shared: 
`from flask import Flask, render_template, request, jsonify, make_response, j>`
The code in the tutorial is as follows: 

from flask import Flask, render_template, request, jsonify, make_response, json

A similar error is present here: 
`auth = pusher.authenticate(channel=request.form['channel_name'],socket_i>`

I would advise that you review your code to ensure it is correct and in line with the tutorial code at https://pusher.com/tutorials/chat-widget-python. 
To assist this the error output you have shared also lets you know where to look for the error. The current error shows: 
`File "/root/python-pusher-chat-widget/app.py", line 1 `
And the error I share above is on line 1.

**Comment by ben-pusher** [comment]
If you require any further support please get in touch with us at https://support.pusher.com/hc/en-us/requests/new, we would like to reserve Github issues for bugs with the library.
