### ISSUE TITLE
Bump pynacl version

### ISSUE THREAD

**Issue by ddhanak** [pusher/pusher-http-python#185]
Hi,

We are currently building multi-architecture images of our internal project and we are using this library which has a dependency on [pynacl](https://github.com/pyca/pynacl). 

The current version of PyNaCl is set to `1.3.0`. We were wondering if it was possible to bump this version to 1.5.0 which supports ARM64 (macOS).

Thanks!

**Comment by benjamin-tang-pusher** [comment]
Hi,

If you install this with Pip, it should use the setup.py and not the requirements.txt to resolve its dependencies, and your project should end up with PyNaCl==1.5.0 . Are you installing with `pip install pusher` ?

I've tried touching the requirements.txt in the past and its quite outdated. For now I'm using `pip install .` if I'm working on the library itself.

**Comment by benjamin-tang-pusher** [comment]
Please reopen if this is still an issue for you, I'm going to close this.
