### ISSUE TITLE
How do I bind to Requests

### ISSUE THREAD

**Issue by imdigitalashish** [pusher/pusher-http-python#192]
Hey, I wanted to know, How can I bind to these requests in python... like we listen in js... how do we listen in the python side?

**Comment by benw-pusher** [comment]
Channels libraries are divided into 2 categories:

Client
Client libraries predominantly consume messages using a [WebSocket interface](https://pusher.com/docs/channels/library_auth_reference/pusher-websockets-protocol). Think of them as subscribers , although it’s possible to publish messages using [Client Events](https://pusher.com/docs/channels/using_channels/events#triggering-client-events).
Server
Server libraries publish messages, request information using [our HTTP API](https://pusher.com/docs/channels/library_auth_reference/rest-api), [authenticate](https://pusher.com/docs/channels/server_api/authenticating-users) users, [authorize](https://pusher.com/docs/channels/server_api/authorizing-users) users, and handle [Webhook](https://pusher.com/docs/channels/server_api/webhooks) calls. Think of them as publishers, although it’s possible to subscribe to messages using [Client Event Webhooks](https://pusher.com/docs/channels/server_api/webhooks#client-events).

This python library is a server library and so it isn't possible to bind to requests as you are looking to do. We do have some [community libraries available](https://pusher.com/docs/channels/channels_libraries/libraries/) which includes a Python client library which may help you here.
