### ISSUE TITLE
PEP 561: Types

### ISSUE THREAD

**Issue by robbieculkin** [pusher/pusher-http-python#196]
Many applications use mypy (or similar) for static typechecking. Anyone using a typechecker needs to explicitly ignore checking on pusher imports, since types don't appear to be defined according to the [PEP 561](https://peps.python.org/pep-0561/) spec. 

Is there anything on the roadmap to add PEP 561 compliance to the package?

**Comment by benjamin-tang-pusher** [comment]
Hi, I ran mypy against pusher.py and couldn't couldn't detect the issue. How are you invoking the command?

```
(venv) benjamintang@Benjamins-MacBook-Pro pusher-http-python % mypy pusher/pusher.py 
Success: no issues found in 1 source file
```

**Comment by robbieculkin** [comment]
While mypy may succeed when running on files in this repo _directly_, the pusher repo needs to provide either 
1. a `py.typed` marker file and type-annotated function signatures
2. a stub package with type definitions
in order to comply with the PEP 561 spec.

**Comment by benjamin-tang-pusher** [comment]
I will add this to our feature requests for our engineering to prioritise.
