### ISSUE TITLE
app_id does not allow dash even though input is string

### ISSUE THREAD

**Issue by johnefemer** [pusher/pusher-http-python#211]
https://github.com/pusher/pusher-http-python/blob/239d67b7a047a18ee181922c0a1461ceaf7c565f/pusher/util.py#L16

app_id should allow uuid type input 
the websocket service i used creates app_id like below
but using this throws an error even though service is valid 

```
app_id='84b182a0-c580-413d-9522-70117b396fda'
key='662c0e50-7d37-4a5c-bce8-da7efa024332'
```

**Comment by benw-pusher** [comment]
This library is designed for use with the Pusher Channels service which does not accept dash in the app ID or keys. 
I recommend you fork the library if you need to change it to make it compatible with other services.
