### ISSUE TITLE
websocket compression capability

### ISSUE THREAD

**Issue by wallawaz** [pusher/pusher-http-python#217]
Hello, I was wondering which versions of this library will continue to be supported with the upcoming [websocket compression change](https://pusher.com/blog/websocket-compression-pusher/#how-will-this-impact-my-implementation) mentioned on your blog which is scheduled for release on 2023-10-18.

Thank you.

**Comment by benw-pusher** [comment]
This library is not affected by this change, this library is for interacting with our HTTP API and it does not create or maintain any websocket connections.
