### ISSUE TITLE
Why do you allow 30720 bytes in pusher_client.py while max 10240 bytes is allowed in your API?

### ISSUE THREAD

**Issue by talboren** [pusher/pusher-http-python#220]
https://github.com/pusher/pusher-http-python/blob/239d67b7a047a18ee181922c0a1461ceaf7c565f/pusher/pusher_client.py#L94C33-L94C33 -> 413: The data content of this event exceeds the allowed maximum (10240 bytes).

**Comment by benw-pusher** [comment]
Our service has a limit of 10kb, however the library has a higher limit to allow specific use cases (where a customer has a dedicated cluster with us).
