### ISSUE TITLE
Tornado example is broken

### ISSUE THREAD

**Issue by mulka** [pusher/pusher-http-python#25]
Getting an error when trying to run the Tornado example:
TypeError: send_request() got an unexpected keyword argument 'timeout'

Only modification was to change the app_id, key, and secret.

**Comment by nullco** [comment]
This commit is not reflected when installing pusher via pip

pip install pusher==0.8
cat /usr/local/lib/python2.7/dist-packages/pusher/__init__.py

result:
...
class TornadoChannel(Channel):
    def trigger(self, event, data={}, socket_id=None, callback=None):
        self.callback = callback
        return super(TornadoChannel, self).trigger(event, data, socket_id)

    def send_request(self, signed_path, data_string):
        import tornado.httpclient
        absolute_url = self.get_absolute_path(signed_path)
        request = tornado.httpclient.HTTPRequest(absolute_url, method='POST', body=data_string)
        client = tornado.httpclient.AsyncHTTPClient()
        client.fetch(request, callback=self.callback)
        # Returning 202 to avoid Channel errors. Actual error handling takes place in callback.
        return 202, ""
....

It seems the older version of this class
