### ISSUE TITLE
python 3 support?

### ISSUE THREAD

**Issue by mulka** [pusher/pusher-http-python#32]
please?

**Comment by mrhwick** [comment]
It appears that Python 3 support is now restored for this library. Would it be possible for you to create a new version of the package for installation with this included?

**Comment by pcsforeducation** [comment]
+1, this is the last library between me and switching to Python 3.4.

**Comment by jpatel531** [comment]
Version 1.0.0 (now on the master branch) now has support for python 3

**Comment by pcsforeducation** [comment]
Awesome! Thanks!
