### ISSUE TITLE
UnexpectedReturnStatusError

### ISSUE THREAD

**Issue by whatsdis** [pusher/pusher-http-python#35]
File "./job.py", line 267, in queue_next_job
    p[str(job.id)].trigger('progress', {'status':'Running', 'jobid':str(job.id)})
  File "/usr/local/lib/python2.7/dist-packages/pusher/**init**.py", line 78, in trigger
    raise UnexpectedReturnStatusError("Status: %s; Message: %s" % (status, resp_content))
pusher.UnexpectedReturnStatusError: Status: 200; Message: {}

I am using the python client (pip install pusher) and coming across this message. The push happens but it keeps complaining about this issue.

**Comment by hot-leaf-juice** [comment]
Closing as probably no longer relevant. (Feel free to reopen if not!)
