### ISSUE TITLE
Problem with google app engine

### ISSUE THREAD

**Issue by kongakong** [pusher/pusher-http-python#54]
I am trying out the latest `master` branch.

First of all, there seems to be a syntax/api issue with  UrlfetchBackend.py

```
--- a/lib/pusher/urlfetch.py
+++ b/lib/pusher/urlfetch.py
@@ -3,7 +3,7 @@
 from __future__ import (print_function, unicode_literals, absolute_import,
                         division)

-import urlfetch
+from google.appengine.api import urlfetch
 from pusher.http import process_response

 class URLFetchBackend(object):
@@ -19,7 +19,7 @@ class URLFetchBackend(object):
       url=request.url,
       headers=request.headers,
       method=request.method,
-      data=request.body,
+      payload=request.body,
       deadline=self.config.timeout,
       **self.options
     )
```

I applied the above patch to get it to run.

Now there is no more runtime exception. Based on my application log I can see I can send message to the pusher server. However my pusher clients (written in javascript) are not receiving any message.

Any suggestion?

 I would also like to know how I can check if I have successfully sent messages to pusher servers, preferably via your some sort of control on pusher website?

**Comment by jpatel531** [comment]
Hi there - thanks for bringing this to our attention - you can check on your debug console on app.pusher.com to see if there's any messages coming through.

What error messages are you messages with the previous syntax?

**Comment by jpatel531** [comment]
As far as I'm aware urlfetch and GAE urlfetch used the same transports - I only used urlfetch with this library (and of course tested it out with GAE) as I thought it would be easier for testing and CI. But I should probably reconsider!

**Comment by powerspowers** [comment]
To get this to work in GAE with python 2.7 I had to do three things:

> update the fetch args to use 'payload' instead of 'data' as you outline above

> to import urlfetch i had to change the import to 'from google.appengine.api import urlfetch'

> six.py is not part of GAE so I replaced any types referring to six with their regular types for python 2.7 (e.g. unicode or (int, long) 

After the above I was able to get this included and successfully send and receive messages on Pusher!

**Comment by jpatel531** [comment]
Hey, version 1.2.0 should have made this fix! Also now the HTTP adapter has been renamed to `pusher.gae.GAEBackend` --- let me know if there are any outstanding issues

**Comment by powerspowers** [comment]
The fetch changes work. What should I do about six.py which is not part of GAE. I have not been able to find the canonical version of it to include. Its also used in only 5 locations in your library so it might be better just to include the types in your code rather than require another 3rd party dependency.

**Comment by zimbatm** [comment]
Which method are you using to install the package ? I think that `pip` or `easy_install` would fetch the associated dependency.

**Comment by powerspowers** [comment]
This is on Google App Engine and I am not sure they enable installers - you have to just move over new files as needed if they are not there already - they include many of the Django libs and such but not six

**Comment by jpatel531** [comment]
@powerspowers does vendoring the six package resolve any issues? I'm fairly new to GAE, and have only vendored dependencies (when testing the library on GAE, six was included within the vendor directory) - is there an alternative I should be aware of?

**Comment by hot-leaf-juice** [comment]
Closing since this looks like it was more or less solved, and hasn't seen any activity in a long time. Feel free to reopen with more details if still relevant.
