### ISSUE TITLE
Pusher Not importing in Django

### ISSUE THREAD

**Issue by IshaanChawla** [pusher/pusher-http-python#66]
I installed pusher-http-python package with pip. 

The sample code provided on pusher website runs from the shell. Hence i know, it has got installed properly. 

But when i try importing pusher into my django view, it raise an IMPORT ERROR : cannot import name Pusher

thanks in advance,
Ishaan

**Comment by wieczorek1990** [comment]
What was the problem?

**Comment by IshaanChawla** [comment]
I really don't remember now, what the problem was. Must have been some naive error I would have been making. Thank You for asking Though
