### ISSUE TITLE
OpenSSL on Ubuntu

### ISSUE THREAD

**Issue by jpatel531** [pusher/pusher-http-python#67]
ImportError: python2.7/site-packages/cryptography/hazmat/bindings/_openssl.so: undefined symbol: EC_KEY_clear_flags

---

Fixed with:

```
$ pip install pyOpenSSL==0.13.
```

Will investigate further. Either will specify dependency or add note in README. (Don't know enough about this yet)

**Comment by WillSewell** [comment]
Not sure how to reproduce. Closing for now. Feel free to re-open if anyone experience this again.
