### ISSUE TITLE
Channel subscription?

### ISSUE THREAD

**Issue by borfast** [pusher/pusher-http-python#69]
Would it be possible to subscribe to channels with this Python library? Especially without having to provide my secret key?

I have a Raspberry Pi where I want to receive Pusher events in a Python program but it seems impossible to do so.

I've been using [this library](https://github.com/ekulyk/PythonPusherClient) but it seems to have some serious problems. For example, the client (apparently) randomly stops calling the event callback when it receives a message from Pusher.

Wouldn't it be possible to have an official Python client library?

Thanks

**Comment by hot-leaf-juice** [comment]
This is an old issue, but for the sake of reference:

Pusher libraries are split in to two types: http libraries for triggering, authenticating private channels, webhooks etc. and websocket libraries for subscribing to channels and listening to events. There are no current plans for an official python websocket library, or to build that functionality in to this library, though people have certainly had some success with community libraries and/or writing their own client that implements the [Pusher websocket protocol](https://pusher.com/docs/pusher_protocol). A list of official libraries can be found [here](https://pusher.com/docs/libraries).

**Comment by borfast** [comment]
OK, fair enough.

Could you say why?

And thanks for replying even after all this time :)

**Comment by hot-leaf-juice** [comment]
No worries – sorry it took so long! I've just inherited this library and thought I'd do some spring cleaning. :)

There just aren't enough people who need a python websocket library for us to justify the resources that would be required to write one. As far as receiving pusher events on the Raspberry Pi goes, the recommended route is to run [the node build of pusher-js](https://github.com/pusher/pusher-js#nodejs) on it.

**Comment by exitcomestothis** [comment]
borfast - What service did you end up going with? 

We've ran into the exact same scenario with Pusher and Python on rPi. I have to say, this is quite disappointing, as Pusher (was) a terrific fit for us, and using a 3rd party library isn't an option for us.

**Comment by hugoamvieira** [comment]
Hello,

We have a community supported Python client side library you can use [here](https://pusher.com/docs/libraries#community-py)

**Comment by borfast** [comment]
@exitcomestothis, I believe it was either [Fanout](https://fanout.io/) or [Google Cloud Pub/Sub](https://cloud.google.com/pubsub/). Can't recall for sure.
