### ISSUE TITLE
Django 1.9: ImportError or AttributeError

### ISSUE THREAD

**Issue by jbreuer95** [pusher/pusher-http-python#70]
When i do:

```
import pusher
p = pusher.Pusher
```

I get:
`AttributeError: 'module' object has no attribute 'Pusher'`

When i do:
```
from pusher import Pusher
p = Pusher
```
I get:
`ImportError: cannot import name Pusher`

**Comment by jpatel531** [comment]
Hey there - which versions of Python and the library are you using? What's the name of the file you're running Pusher in? Can you make sure it's not `pusher.py`?

**Comment by jbreuer95** [comment]
Python 2.7.11
Pusher 1.20
views.py in my Django app

**Comment by jbreuer95** [comment]
My bad! Called my Django project pusher xD

**Comment by jpatel531** [comment]
Glad to hear it :)

**Comment by deepeshk79** [comment]
Have the same error in Python Flask.. 
`import pusher

pusher_client = pusher.Pusher(
  app_id='appid',
  key='keyhere',
  secret='##',
  cluster='ap2',
  ssl=True
)

pusher_client.trigger('my-channel', 'my-event', {'message': 'hello world'})`

pusher_client = pusher.Pusher(
AttributeError: 'module' object has no attribute 'Pusher'

This is the same code in sample, why is this failing ?

**Comment by deepeshk79** [comment]
Nope its viewmyapp.py

**Comment by leesio** [comment]
It certainly looks like `pusher` is being overwritten by something else. Is there a `pusher.py` or a `pusher.pyc` in the same directory as your application? What happens when you `print(pusher)` after importing?

**Comment by deepeshk79** [comment]
yes just noticed there is a pusher.pyc in the same directory, not sure how that got created... how does it impact ? Should i move my viewmyapp.py to a diff directory ?

**Comment by deepeshk79** [comment]
The print(pusher)

<module 'pusher' from '/Users/deepesh/Desktop/flaskapp/pusher.pyc'>

**Comment by leesio** [comment]
Basically your application will import the `pusher.pyc` file instead of the actual `pusher` library.
As you can see from the `print` 😊

You should be safe to remove the `pusher.pyc` file.

**Comment by deepeshk79** [comment]
cool that fixed the issue, but then it failed for cryptography pkg, installed it and now it fails for pyOpenSSL, trying to fix that..

**Comment by MidoCobra** [comment]
i have the same problem .. python 3.6 .. 
and i haven any pusher. files in my app ..
need some help please

**Comment by WillSewell** [comment]
@MidoCobra Could you send the complete code and steps to reproduce the problem?

**Comment by mirrormirage0** [comment]
I faced the same issue.
I think its important to add to readme or even the sample code "Do not name your file as pusher.py" 
And if you did, delete the pusher.pyc which gets created :)
Got it working now.
