### ISSUE TITLE
Shouldn't users_info also return the "user_info" data inside "custom_data" dict?

### ISSUE THREAD

**Issue by diegopau** [pusher/pusher-http-python#71]
I am trying to retrieve information of the users currently online in a chat room (users subscribed to a pusher channel).

When a user subscribes to the channel the following info is sent to pusher from the Django server:

channel_data
```
{
    'user_id': socket_id,  
    'user_info': {  
        'public_name': profile.public_name,  
        'username': profile.username  
    }  
}  

auth_response = pusher_object.authenticate(  
    channel=chat_channel,  
    socket_id=socket_id,  
    custom_data=channel_data  
)  
```

I was expecting to be able to retrieve this data, also from my Django server. But the only method I see in this library is Pusher::users_info which only seems to fetch the a dictionary containing the user_id of each subscribed user. Is there any way to retrieve also the user_info for each user? whats the reason for including it in the authenticate method if not?

**Comment by topliceanu** [comment]
hi @diegopau 

Are you still experiencing this error? 

This error coincides with some issues we had on the service. See https://status.pusher.com/incidents/368yzqsk13xy

**Comment by diegopau** [comment]
It is not related with this. I don't consider this an error, I am just asking about the implementation of both Pusher protocol and the python library. Can you confirm me if there is a way to retrieve the "user_info" dictionary, inside "custom_data" of each subscribed user in a presence channel? I am only able to retrieve the "user_id" field inside "custom_data" using Pusher::users_info, but not what is inside "user_info" (which is a python dictionary).

**Comment by topliceanu** [comment]
Hi @diegopau 

No, it only returns the user ids. It's contacting this endpoint https://pusher.com/docs/rest_api#method-get-users

The idea is that you attach custom data to the user when you authenticate him/her so that it's visible on the client-side. It is assumed that you already have this data store on the server side. 

I hope that helps,
Alex

**Comment by diegopau** [comment]
@topliceanu thanks for the info. Makes sense, I am using now the user_id to get the rest of the data on the server side. I assume then that the custom data can be retrieved with any of the client libraries available.
I am closing the issue as it all seems clear now!

**Comment by topliceanu** [comment]
@diegopau Yes, at the very least the user data is available on all supported client libraries, I'm not sure about the others. You can see a list of pusher libs here: https://pusher.com/docs/libraries
