### ISSUE TITLE
About semantic versioning and backward compatibility

### ISSUE THREAD

**Issue by iurisilvio** [pusher/pusher-http-python#86]
The version 1.6 is not backwards compatible with 1.5. Now, all configuration is hidden inside a `_pusher_client` object. It happened in commit 2e71da394ef5b5d02e933b47aecf35a36de31a27.

For example, I use `pusher.key` in Flask-Pusher package and it failed with 1.6+. I had to make a workaround to fix all my tests and probably you can use the same solution to make it compatible. https://github.com/iurisilvio/Flask-Pusher/commit/4be823fed81b6a37406f5c65386c785329a8f24d

Semantic versioning is important to third-party applications. If you want to break compatibility, change the major version.

**Comment by WillSewell** [comment]
Thanks for making us aware of this. Currently we are following semantic versioning; unfortunately we can't go back and change the past 😕
