### ISSUE TITLE
Timeouts using Push Notification feature

### ISSUE THREAD

**Issue by kangaroosterussave** [pusher/pusher-http-python#89]
Calling the Pusher notify method **often** (but not always) results in a timeout.

For example doing something like:

> pusher = Pusher(app_id=app_id,
>                 key=key,
>                 secret=secret,
>                 timeout=1,
>                 retry=5, # THE DEFAULT
>                 ssl=False)
> 
> pusher.notify([channel], notification)

Results in:

> requests.exceptions.ReadTimeout: HTTPSConnectionPool(host='nativepush-cluster1.pusher.com', > port=443): Read timed out. (read timeout=1)

Any ideas?

**Comment by kangaroosterus** [comment]
Also, when I set the timeout to a large enough number (ie. timeout=60), 
 I'm getting HTTP Service Unavailable status code:

> pusher.errors.PusherBadStatus: 503:

**Comment by vivangkumar** [comment]
@kangaroosterus Hi there!

We're investigating availability issues with the Push Notification API. A fix is currently being developed and should hopefully resolve these issues soon.

Apologies for any inconvenience.

**Comment by hot-leaf-juice** [comment]
@kangaroosterus Are you still seeing these timeouts? We've made some changes to the backend which should hopefully have improved the situation.

**Comment by tySwift93** [comment]
I am seeing timeout exceptions like this:
```python
requests.exceptions.ReadTimeout: HTTPSConnectionPool(host='nativepush-cluster1.pusher.com', port=443): Read timed out. (read timeout=5)
```

**Comment by hot-leaf-juice** [comment]
Hi @tySwift93, we were experiencing some issues earlier today that could have caused this – though they should be resolved now. Are you still seeing the timeouts?

**Comment by tySwift93** [comment]
Not anymore, thank you

**Comment by WillSewell** [comment]
Closing because it appears this issue was resolved, and we are deprecating Push Notifications support in this library anyway.
