### ISSUE TITLE
Pusher object creation fails

### ISSUE THREAD

**Issue by intellimindZ** [pusher/pusher-http-python#95]
I used pusher library under python versions 2.7.6, 2.7.9 and 2.7.13. While executing following code, it generates following error within python/flask application.

from pusher import Pusher
pusher = Pusher(app_id=app_id, key=key, secret=secret, ssl=True)

>>> ("'pyOpenSSL' module missing required functionality. Try upgrading to v0.14 or newer.",)

After performing following steps, it didn't help.

1. Install pyopenssl 0.14
pip install pyOpenSSL==0.14.

2. Removed ssl=True argument
Pusher(app_id=app_id, key=key, secret=secret)

3. Taking latest version of pusher
pip install -e git+https://github.com/pusher/pusher-http-python.git#egg=pusher

Appreciate any help with above issue.

**Comment by hot-leaf-juice** [comment]
Can we see the full stacktrace to see if we can get a better idea where the problem might be? What OS are you running? pyopenssl seems to cause a lot of these kinds of problems... https://github.com/certbot/certbot/issues/4514

**Comment by intellimind** [comment]
For now, I could resolve this issue by removing older version of pyopenssl on ubuntu 14.04

**Comment by WillSewell** [comment]
Closing because there is no "fix" for us to make in the library. It's up to the users to resolve their dependencies in this case.
