### ISSUE TITLE
How can I stream Bitstamp's websocket?

### ISSUE THREAD

**Issue by zlwolf236** [pusher/pusher-http-python#99]
I just couldn't figure out how to hook myself to bitstamp's websocket. Please help and it will be very very much appreciated! Thank You

https://www.bitstamp.net/websocket/

**Comment by hot-leaf-juice** [comment]
Pusher libraries are either "http" or "websocket". This is a http library, so you can use it to trigger events and authenticate private channels, but you can't use it to subscribe to websockets. For a list of our websocket libraries [see here](https://pusher.com/docs/libraries#official-client-libraries).
